In [1]:
import json
import re
import time
from datetime import datetime
from pathlib import Path

import requests
from bs4 import BeautifulSoup

In [2]:
# =========================
# 0. 기본 경로 설정
# =========================
PROJECT_ROOT = Path(r"C:\Users\asguug\Documents\rag-agent")

RAW_DIR = PROJECT_ROOT / "data" / "raw"
DOCS_DIR = PROJECT_ROOT / "data" / "docs"
CHROMA_DIR = PROJECT_ROOT / "data" / "chroma_db"

RAW_DIR.mkdir(parents=True, exist_ok=True)
DOCS_DIR.mkdir(parents=True, exist_ok=True)
CHROMA_DIR.mkdir(parents=True, exist_ok=True)

print("PROJECT_ROOT:", PROJECT_ROOT)
print("RAW_DIR:", RAW_DIR)
print("DOCS_DIR:", DOCS_DIR)
print("CHROMA_DIR:", CHROMA_DIR)

PROJECT_ROOT: C:\Users\asguug\Documents\rag-agent
RAW_DIR: C:\Users\asguug\Documents\rag-agent\data\raw
DOCS_DIR: C:\Users\asguug\Documents\rag-agent\data\docs
CHROMA_DIR: C:\Users\asguug\Documents\rag-agent\data\chroma_db

In [3]:
GAMES = {
    "hollow_knight": {
        "appid": 367520,
        "title": "Hollow Knight",
    },
    "monster_hunter_world": {
        "appid": 582010,
        "title": "Monster Hunter: World",
    },
    "baldurs_gate_3": {
        "appid": 1086940,
        "title": "Baldur's Gate 3",
    },
    "no_mans_sky": {
        "appid": 275850,
        "title": "No Man's Sky",
    },
    "cyberpunk_2077": {
        "appid": 1091500,
        "title": "Cyberpunk 2077",
    },
}

GAMES

{'hollow_knight': {'appid': 367520, 'title': 'Hollow Knight'},
 'monster_hunter_world': {'appid': 582010, 'title': 'Monster Hunter: World'},
 'baldurs_gate_3': {'appid': 1086940, 'title': "Baldur's Gate 3"},
 'no_mans_sky': {'appid': 275850, 'title': "No Man's Sky"},
 'cyberpunk_2077': {'appid': 1091500, 'title': 'Cyberpunk 2077'}}

In [4]:
def clean_html(raw_html: str) -> str:
    """Steam 설명/뉴스 HTML을 일반 텍스트로 변환한다."""
    if not raw_html:
        return ""

    soup = BeautifulSoup(raw_html, "html.parser")
    text = soup.get_text(separator="\n")
    text = re.sub(r"\n{3,}", "\n\n", text)
    text = re.sub(r"[ \t]+", " ", text)
    return text.strip()


def unix_to_date(ts) -> str:
    """Unix timestamp를 YYYY-MM-DD 문자열로 변환한다."""
    if not ts:
        return ""

    try:
        return datetime.fromtimestamp(int(ts)).strftime("%Y-%m-%d")
    except Exception:
        return ""


def save_json(path: Path, data: dict) -> None:
    """원본 JSON 저장."""
    with path.open("w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)


def safe_get_json(url: str, params: dict | None = None, timeout: int = 20) -> dict:
    """GET 요청 후 JSON 반환. 실패하면 빈 dict 반환."""
    try:
        response = requests.get(
            url,
            params=params,
            timeout=timeout,
            headers={
                "User-Agent": "Mozilla/5.0 (baseline-rag-study)"
            },
        )
        response.raise_for_status()
        return response.json()
    except Exception as e:
        print(f"[WARN] 요청 실패: {url}")
        print(f"       이유: {e}")
        return {}

print("utils OK")

utils OK

In [5]:
def fetch_app_details(appid: int) -> dict:
    """
    Steam Store appdetails 정보 수집.
    baseline 문서 생성용으로 사용한다.
    """
    url = "https://store.steampowered.com/api/appdetails"
    params = {
        "appids": appid,
        "l": "english",
        "cc": "US",
    }
    return safe_get_json(url, params=params)


def fetch_reviews(appid: int, num_per_page: int = 20) -> dict:
    """
    Steam 최근 리뷰 수집.
    3주차 baseline에서는 20개만 사용한다.
    """
    url = f"https://store.steampowered.com/appreviews/{appid}"
    params = {
        "json": 1,
        "filter": "recent",
        "language": "english",
        "review_type": "all",
        "purchase_type": "all",
        "num_per_page": num_per_page,
    }
    return safe_get_json(url, params=params)


def fetch_news(appid: int, count: int = 5) -> dict:
    """Steam News / Patch note 수집."""
    url = "https://api.steampowered.com/ISteamNews/GetNewsForApp/v2/"
    params = {
        "appid": appid,
        "count": count,
        "maxlength": 2000,
        "format": "json",
    }
    return safe_get_json(url, params=params)

print("fetch functions OK")

fetch functions OK

In [6]:
def build_markdown(game_key: str, game_info: dict, app_details: dict, reviews: dict, news: dict) -> str:
    appid = game_info["appid"]
    title = game_info["title"]

    detail_data = {}
    if str(appid) in app_details:
        detail_data = app_details.get(str(appid), {}).get("data", {}) or {}

    short_description = clean_html(detail_data.get("short_description", ""))
    about_the_game = clean_html(detail_data.get("about_the_game", ""))
    detailed_description = clean_html(detail_data.get("detailed_description", ""))

    genres = detail_data.get("genres", []) or []
    genre_text = ", ".join([g.get("description", "") for g in genres if g.get("description")])

    categories = detail_data.get("categories", []) or []
    category_text = ", ".join([c.get("description", "") for c in categories if c.get("description")])

    release_date = detail_data.get("release_date", {}).get("date", "")
    developers = ", ".join(detail_data.get("developers", []) or [])
    publishers = ", ".join(detail_data.get("publishers", []) or [])

    review_items = reviews.get("reviews", []) or []
    news_items = news.get("appnews", {}).get("newsitems", []) or []

    lines = []

    lines.append(f"# {title}")
    lines.append("")
    lines.append("## Metadata")
    lines.append(f"- game_key: {game_key}")
    lines.append(f"- appid: {appid}")
    lines.append(f"- title: {title}")
    lines.append(f"- release_date: {release_date}")
    lines.append(f"- developers: {developers}")
    lines.append(f"- publishers: {publishers}")
    lines.append(f"- genres: {genre_text}")
    lines.append(f"- categories: {category_text}")
    lines.append("")

    lines.append("## Store Summary")
    lines.append(short_description if short_description else "No short description found.")
    lines.append("")

    lines.append("## About The Game")
    if about_the_game:
        lines.append(about_the_game)
    elif detailed_description:
        lines.append(detailed_description)
    else:
        lines.append("No detailed store description found.")
    lines.append("")

    lines.append("## Recent Steam Reviews")
    if review_items:
        for idx, review in enumerate(review_items, start=1):
            voted_up = review.get("voted_up")
            sentiment = "positive" if voted_up else "negative"
            created_at = unix_to_date(review.get("timestamp_created"))
            updated_at = unix_to_date(review.get("timestamp_updated"))
            playtime = review.get("author", {}).get("playtime_forever", 0)
            playtime_hours = round(playtime / 60, 1) if playtime else 0
            review_text = clean_html(review.get("review", ""))

            lines.append(f"### Review {idx}")
            lines.append(f"- sentiment: {sentiment}")
            lines.append(f"- created_at: {created_at}")
            lines.append(f"- updated_at: {updated_at}")
            lines.append(f"- playtime_hours: {playtime_hours}")
            lines.append("")
            lines.append(review_text[:1500])
            lines.append("")
    else:
        lines.append("No recent reviews found.")
        lines.append("")

    lines.append("## Steam News and Updates")
    if news_items:
        for idx, item in enumerate(news_items, start=1):
            news_title = item.get("title", "")
            news_date = unix_to_date(item.get("date"))
            contents = clean_html(item.get("contents", ""))

            lines.append(f"### News {idx}: {news_title}")
            lines.append(f"- date: {news_date}")
            lines.append("")
            lines.append(contents[:2000])
            lines.append("")
    else:
        lines.append("No news items found.")
        lines.append("")

    return "\n".join(lines)

print("markdown function OK")

markdown function OK

In [7]:
for game_key, game_info in GAMES.items():
    appid = game_info["appid"]
    title = game_info["title"]

    print(f"[INFO] Collecting: {title} ({appid})")

    app_details = fetch_app_details(appid)
    reviews = fetch_reviews(appid, num_per_page=20)
    news = fetch_news(appid, count=5)

    save_json(RAW_DIR / f"{game_key}_app_details.json", app_details)
    save_json(RAW_DIR / f"{game_key}_reviews.json", reviews)
    save_json(RAW_DIR / f"{game_key}_news.json", news)

    markdown = build_markdown(
        game_key=game_key,
        game_info=game_info,
        app_details=app_details,
        reviews=reviews,
        news=news,
    )

    output_path = DOCS_DIR / f"{game_key}.md"
    output_path.write_text(markdown, encoding="utf-8")

    print(f"[OK] Saved markdown: {output_path}")
    print("")

    time.sleep(1)

print("[DONE] Steam baseline documents created.")

[INFO] Collecting: Hollow Knight (367520)
[OK] Saved markdown: C:\Users\asguug\Documents\rag-agent\data\docs\hollow_knight.md

[INFO] Collecting: Monster Hunter: World (582010)
[OK] Saved markdown: C:\Users\asguug\Documents\rag-agent\data\docs\monster_hunter_world.md

[INFO] Collecting: Baldur's Gate 3 (1086940)
[OK] Saved markdown: C:\Users\asguug\Documents\rag-agent\data\docs\baldurs_gate_3.md

[INFO] Collecting: No Man's Sky (275850)
[OK] Saved markdown: C:\Users\asguug\Documents\rag-agent\data\docs\no_mans_sky.md

[INFO] Collecting: Cyberpunk 2077 (1091500)
[OK] Saved markdown: C:\Users\asguug\Documents\rag-agent\data\docs\cyberpunk_2077.md

[DONE] Steam baseline documents created.

In [8]:
md_files = sorted(DOCS_DIR.glob("*.md"))

print("생성된 Markdown 문서 수:", len(md_files))
for path in md_files:
    print("-", path.name)

생성된 Markdown 문서 수: 5
- baldurs_gate_3.md
- cyberpunk_2077.md
- hollow_knight.md
- monster_hunter_world.md
- no_mans_sky.md

In [9]:
from langchain_community.document_loaders import DirectoryLoader, TextLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter

loader = DirectoryLoader(
    path=str(DOCS_DIR),
    glob="*.md",
    loader_cls=TextLoader,
    loader_kwargs={"encoding": "utf-8"},
)

docs = loader.load()

print("로드된 문서 개수:", len(docs))

for i, doc in enumerate(docs):
    print(f"\n--- Document {i+1} ---")
    print("source:", doc.metadata.get("source"))
    print("content length:", len(doc.page_content))
    print(doc.page_content[:300])

로드된 문서 개수: 5

--- Document 1 ---
source: C:\Users\asguug\Documents\rag-agent\data\docs\baldurs_gate_3.md
content length: 14069
# Baldur's Gate 3

## Metadata
- game_key: baldurs_gate_3
- appid: 1086940
- title: Baldur's Gate 3
- release_date: Aug 3, 2023
- developers: Larian Studios
- publishers: Larian Studios
- genres: Adventure, RPG, Strategy
- categories: Single-player, Multi-player, Co-op, Online Co-op, LAN Co-op, Cros

--- Document 2 ---
source: C:\Users\asguug\Documents\rag-agent\data\docs\cyberpunk_2077.md
content length: 6752
# Cyberpunk 2077

## Metadata
- game_key: cyberpunk_2077
- appid: 1091500
- title: Cyberpunk 2077
- release_date: Dec 9, 2020
- developers: CD PROJEKT RED
- publishers: CD PROJEKT RED
- genres: RPG
- categories: Single-player, Steam Achievements, Full controller support, Steam Trading Cards, Adjusta

--- Document 3 ---
source: C:\Users\asguug\Documents\rag-agent\data\docs\hollow_knight.md
content length: 10256
# Hollow Knight

## Metadata
- game_key: hollow_knight
- appid: 367520
- title: Hollow Knight
- release_date: Feb 24, 2017
- developers: Team Cherry
- publishers: Team Cherry
- genres: Action, Adventure, Indie
- categories: Single-player, Steam Achievements, Full controller support, Steam Trading Ca

--- Document 4 ---
source: C:\Users\asguug\Documents\rag-agent\data\docs\monster_hunter_world.md
content length: 14354
# Monster Hunter: World

## Metadata
- game_key: monster_hunter_world
- appid: 582010
- title: Monster Hunter: World
- release_date: Aug 8, 2018
- developers: CAPCOM Co., Ltd.
- publishers: CAPCOM Co., Ltd.
- genres: Action
- categories: Single-player, Multi-player, Co-op, Steam Achievements, Steam

--- Document 5 ---
source: C:\Users\asguug\Documents\rag-agent\data\docs\no_mans_sky.md
content length: 16266
# No Man's Sky

## Metadata
- game_key: no_mans_sky
- appid: 275850
- title: No Man's Sky
- release_date: Aug 12, 2016
- developers: Hello Games
- publishers: Hello Games
- genres: Action, Adventure
- categories: Single-player, Multi-player, PvP, Online PvP, Co-op, Online Co-op, Cross-Platform Multi

In [10]:
from langchain_core.documents import Document

def infer_game_key_from_source(source: str) -> str:
    filename = Path(source).stem
    return filename


def split_markdown_by_sections(doc):
    """
    하나의 게임 md 문서를 section 단위 Document로 분리한다.
    section metadata를 붙여서 review/news 검색을 구분하기 쉽게 만든다.
    """
    source = doc.metadata.get("source", "")
    game_key = infer_game_key_from_source(source)
    text = doc.page_content

    section_patterns = [
        ("metadata", "## Metadata"),
        ("store_summary", "## Store Summary"),
        ("about", "## About The Game"),
        ("review", "## Recent Steam Reviews"),
        ("news", "## Steam News and Updates"),
    ]

    sections = []

    for idx, (section_name, heading) in enumerate(section_patterns):
        start = text.find(heading)

        if start == -1:
            continue

        if idx + 1 < len(section_patterns):
            next_heading = section_patterns[idx + 1][1]
            end = text.find(next_heading, start + len(heading))
            if end == -1:
                end = len(text)
        else:
            end = len(text)

        section_text = text[start:end].strip()

        if section_text:
            sections.append(
                Document(
                    page_content=section_text,
                    metadata={
                        "source": source,
                        "game_key": game_key,
                        "section": section_name,
                    },
                )
            )

    return sections


section_docs = []

for doc in docs:
    section_docs.extend(split_markdown_by_sections(doc))

print("원본 문서 개수:", len(docs))
print("section 문서 개수:", len(section_docs))

for d in section_docs[:10]:
    print(Path(d.metadata["source"]).name, d.metadata["game_key"], d.metadata["section"], len(d.page_content))

원본 문서 개수: 5
section 문서 개수: 25
baldurs_gate_3.md baldurs_gate_3 metadata 636
baldurs_gate_3.md baldurs_gate_3 store_summary 224
baldurs_gate_3.md baldurs_gate_3 about 5376
baldurs_gate_3.md baldurs_gate_3 review 5101
baldurs_gate_3.md baldurs_gate_3 news 2704
cyberpunk_2077.md cyberpunk_2077 metadata 514
cyberpunk_2077.md cyberpunk_2077 store_summary 195
cyberpunk_2077.md cyberpunk_2077 about 65
cyberpunk_2077.md cyberpunk_2077 review 3512
cyberpunk_2077.md cyberpunk_2077 news 2439

In [11]:
CHUNK_SIZE = 800
CHUNK_OVERLAP = 120

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=CHUNK_SIZE,
    chunk_overlap=CHUNK_OVERLAP,
    length_function=len,
    separators=["\n\n", "\n", " ", ""],
)

splits = text_splitter.split_documents(section_docs)

print("원본 문서 개수:", len(docs))
print("section 문서 개수:", len(section_docs))
print("생성된 chunk 개수:", len(splits))
print("chunk_size:", CHUNK_SIZE)
print("chunk_overlap:", CHUNK_OVERLAP)

for i, chunk in enumerate(splits[:5], start=1):
    print("\n--- chunk", i, "---")
    print(chunk.metadata)
    print(chunk.page_content[:300])

원본 문서 개수: 5
section 문서 개수: 25
생성된 chunk 개수: 115
chunk_size: 800
chunk_overlap: 120

--- chunk 1 ---
{'source': 'C:\\Users\\asguug\\Documents\\rag-agent\\data\\docs\\baldurs_gate_3.md', 'game_key': 'baldurs_gate_3', 'section': 'metadata'}
## Metadata
- game_key: baldurs_gate_3
- appid: 1086940
- title: Baldur's Gate 3
- release_date: Aug 3, 2023
- developers: Larian Studios
- publishers: Larian Studios
- genres: Adventure, RPG, Strategy
- categories: Single-player, Multi-player, Co-op, Online Co-op, LAN Co-op, Cross-Platform Multipla

--- chunk 2 ---
{'source': 'C:\\Users\\asguug\\Documents\\rag-agent\\data\\docs\\baldurs_gate_3.md', 'game_key': 'baldurs_gate_3', 'section': 'store_summary'}
## Store Summary
Baldur’s Gate 3 is a story-rich, party-based RPG set in the universe of Dungeons & Dragons, where your choices shape a tale of fellowship and betrayal, survival and sacrifice, and the lure of absolute power.

--- chunk 3 ---
{'source': 'C:\\Users\\asguug\\Documents\\rag-agent\\data\\docs\\baldurs_gate_3.md', 'game_key': 'baldurs_gate_3', 'section': 'about'}
## About The Game
Gather your party and return to the Forgotten Realms in a tale of fellowship and betrayal, sacrifice and survival, and the lure of absolute power.
Mysterious abilities are awakening inside you, drawn from a mind flayer parasite planted in your brain. Resist, and turn darkness again

--- chunk 4 ---
{'source': 'C:\\Users\\asguug\\Documents\\rag-agent\\data\\docs\\baldurs_gate_3.md', 'game_key': 'baldurs_gate_3', 'section': 'about'}
From the creators of Divinity: Original Sin 2 comes a next-generation RPG, set in the world of Dungeons & Dragons.
Choose from 12 classes and 11 races from the D&D Player's Handbook and create your own identity, or play as an Origin hero with a hand-crafted background. Or tangle with your inner corr

--- chunk 5 ---
{'source': 'C:\\Users\\asguug\\Documents\\rag-agent\\data\\docs\\baldurs_gate_3.md', 'game_key': 'baldurs_gate_3', 'section': 'about'}
Abducted, infected, lost. You are turning into a monster, but as the corruption inside you grows, so does your power. That power may help you to survive, but there will be a price to pay, and more than any ability, the bonds of trust that you build within your party could be your greatest strength.

In [12]:
for i, chunk in enumerate(splits[:3]):
    print(f"\n==================== Chunk {i+1} ====================")
    print("source:", chunk.metadata.get("source"))
    print("length:", len(chunk.page_content))
    print(chunk.page_content[:1000])

==================== Chunk 1 ====================
source: C:\Users\asguug\Documents\rag-agent\data\docs\baldurs_gate_3.md
length: 636
## Metadata
- game_key: baldurs_gate_3
- appid: 1086940
- title: Baldur's Gate 3
- release_date: Aug 3, 2023
- developers: Larian Studios
- publishers: Larian Studios
- genres: Adventure, RPG, Strategy
- categories: Single-player, Multi-player, Co-op, Online Co-op, LAN Co-op, Cross-Platform Multiplayer, Steam Achievements, Full controller support, Steam Trading Cards, Adjustable Text Size, Camera Comfort, Color Alternatives, Custom Volume Controls, Adjustable Difficulty, Playable without Timed Input, Save Anytime, Stereo Sound, Subtitle Options, Surround Sound, Steam Cloud, Remote Play on TV, Remote Play Together, Family Sharing

==================== Chunk 2 ====================
source: C:\Users\asguug\Documents\rag-agent\data\docs\baldurs_gate_3.md
length: 224
## Store Summary
Baldur’s Gate 3 is a story-rich, party-based RPG set in the universe of Dungeons & Dragons, where your choices shape a tale of fellowship and betrayal, survival and sacrifice, and the lure of absolute power.

==================== Chunk 3 ====================
source: C:\Users\asguug\Documents\rag-agent\data\docs\baldurs_gate_3.md
length: 474
## About The Game
Gather your party and return to the Forgotten Realms in a tale of fellowship and betrayal, sacrifice and survival, and the lure of absolute power.
Mysterious abilities are awakening inside you, drawn from a mind flayer parasite planted in your brain. Resist, and turn darkness against itself. Or embrace corruption, and become ultimate evil.
From the creators of Divinity: Original Sin 2 comes a next-generation RPG, set in the world of Dungeons & Dragons.

In [13]:
from collections import Counter

source_counter = Counter()

for chunk in splits:
    source = Path(chunk.metadata.get("source", "")).name
    source_counter[source] += 1

for source, count in source_counter.items():
    print(f"{source}: {count} chunks")

baldurs_gate_3.md: 24 chunks
cyberpunk_2077.md: 13 chunks
hollow_knight.md: 19 chunks
monster_hunter_world.md: 30 chunks
no_mans_sky.md: 29 chunks

In [14]:
baseline_summary = {
    "document_count": len(docs),
    "chunk_count": len(splits),
    "chunk_size": CHUNK_SIZE,
    "chunk_overlap": CHUNK_OVERLAP,
    "source_files": [Path(doc.metadata.get("source", "")).name for doc in docs],
}

baseline_summary

{'document_count': 5,
 'chunk_count': 115,
 'chunk_size': 800,
 'chunk_overlap': 120,
 'source_files': ['baldurs_gate_3.md',
  'cyberpunk_2077.md',
  'hollow_knight.md',
  'monster_hunter_world.md',
  'no_mans_sky.md']}

In [15]:
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_chroma import Chroma
import os

os.environ["HF_HUB_DISABLE_SYMLINKS_WARNING"] = "1"

EMBEDDING_MODEL_NAME = "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"

embeddings = HuggingFaceEmbeddings(
    model_name=EMBEDDING_MODEL_NAME,
    model_kwargs={"device": "cpu"},
    encode_kwargs={"normalize_embeddings": True},
)

print("Embedding model loaded:", EMBEDDING_MODEL_NAME)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Embedding model loaded: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2

In [16]:
import shutil
if CHROMA_DIR.exists():
    shutil.rmtree(CHROMA_DIR)

CHROMA_DIR.mkdir(parents=True, exist_ok=True)

COLLECTION_NAME = "steam_week3_baseline"

vectorstore = Chroma.from_documents(
    documents=splits,
    embedding=embeddings,
    collection_name=COLLECTION_NAME,
    persist_directory=str(CHROMA_DIR),
)

print("Chroma vectorstore recreated")
print("chunk_count:", len(splits))

Chroma vectorstore recreated
chunk_count: 115

In [17]:

general_retriever = vectorstore.as_retriever(
    search_type="similarity",
    search_kwargs={"k": 4},
)

review_retriever = vectorstore.as_retriever(
    search_type="similarity",
    search_kwargs={
        "k": 4,
        "filter": {"section": "review"},
    },
)

news_retriever = vectorstore.as_retriever(
    search_type="similarity",
    search_kwargs={
        "k": 4,
        "filter": {"section": "news"},
    },
)

print("retrievers created")

retrievers created

In [18]:
test_cases = [
    ("general", "Hollow Knight는 어떤 플레이 스타일의 게임인가요?", general_retriever),
    ("general", "Monster Hunter: World의 핵심 플레이 루프는 무엇인가요?", general_retriever),
    ("review", "Cyberpunk 2077 최근 리뷰에서는 어떤 반응이 있나요?", review_retriever),
    ("news", "No Man's Sky는 업데이트와 관련해서 어떤 내용이 있나요?", news_retriever),
]

for intent, query, selected_retriever in test_cases:
    print("\n" + "=" * 80)
    print("Intent:", intent)
    print("Query:", query)

    retrieved_docs = selected_retriever.invoke(query)

    for i, doc in enumerate(retrieved_docs, start=1):
        source = Path(doc.metadata.get("source", "")).name
        section = doc.metadata.get("section")
        preview = doc.page_content[:300].replace("\n", " ")
        print(f"[{i}] source={source} | section={section} | preview={preview}")

================================================================================
Intent: general
Query: Hollow Knight는 어떤 플레이 스타일의 게임인가요?
[1] source=hollow_knight.md | section=about | preview=Hollow Knight is a classically styled 2D action adventure across a vast interconnected world. Explore twisting caverns, ancient cities and deadly wastes; battle tainted creatures and befriend bizarre bugs; and solve ancient mysteries at the kingdom's heart.  Game Features Classic side-scrolling acti
[2] source=hollow_knight.md | section=store_summary | preview=## Store Summary Forge your own path in Hollow Knight! An epic action adventure through a vast ruined kingdom of insects and heroes. Explore twisting caverns, battle tainted creatures and befriend bizarre bugs, all in a classic, hand-drawn 2D style.
[3] source=hollow_knight.md | section=about | preview=Complete Hollow Knight to unlock Steel Soul Mode, the ultimate challenge!  An Evocative Hand-Crafted World The world of Hollow Knight is brought to life in vivid, moody detail, its caverns alive with bizarre and terrifying creatures, each animated by hand in a traditional 2D style.  Every new area y
[4] source=hollow_knight.md | section=metadata | preview=## Metadata - game_key: hollow_knight - appid: 367520 - title: Hollow Knight - release_date: Feb 24, 2017 - developers: Team Cherry - publishers: Team Cherry - genres: Action, Adventure, Indie - categories: Single-player, Steam Achievements, Full controller support, Steam Trading Cards, Steam Cloud,

================================================================================
Intent: general
Query: Monster Hunter: World의 핵심 플레이 루프는 무엇인가요?
[1] source=monster_hunter_world.md | section=news | preview=Monster Hunter Stories is an RPG series set in the world of Monster Hunter, where you become a Rider and form bonds with monsters, fighting alongside them as you embark on a journey with your friends. The third entry, Monster Hunter Stories 3: Twisted Reflection, is available from today, March 13th!
[2] source=monster_hunter_world.md | section=news | preview={STEAM_CLAN_IMAGE}/45725708/73392ac8e0f10e408b3ebd3d9b846200ca7845a2.png A free trial for Monster Hunter Stories 3: Twisted Reflection lets you get a taste of the game before its March 13, 2026 release. In addition to jumping right into the beginning of the story, you'll be able to customize your ch
[3] source=monster_hunter_world.md | section=store_summary | preview=## Store Summary Welcome to a new world! In Monster Hunter: World, the latest installment in the series, you can enjoy the ultimate hunting experience, using everything at your disposal to hunt monsters in a new world teeming with surprises and excitement.
[4] source=monster_hunter_world.md | section=about | preview=## About The Game Welcome to a new world! Take on the role of a hunter and slay ferocious monsters in a living, breathing ecosystem where you can use the landscape and its diverse inhabitants to get the upper hand. Hunt alone or in co-op with up to three other players, and use materials collected fr

================================================================================
Intent: review
Query: Cyberpunk 2077 최근 리뷰에서는 어떤 반응이 있나요?
[1] source=cyberpunk_2077.md | section=review | preview=### Review 12 - sentiment: positive - created_at: 2026-05-03 - updated_at: 2026-05-03 - playtime_hours: 197.4  Such a beautiful and well-crafted story. Amazing modding support, amazing characters, and meaningful opportunities. This will forever be my favorite game of all time, there is truly no othe
[2] source=no_mans_sky.md | section=review | preview=### Review 20 - sentiment: positive - created_at: 2026-05-03 - updated_at: 2026-05-03 - playtime_hours: 73.3  Comeback of the century
[3] source=cyberpunk_2077.md | section=review | preview=## Recent Steam Reviews ### Review 1 - sentiment: positive - created_at: 2026-05-03 - updated_at: 2026-05-03 - playtime_hours: 66.1  Great  ### Review 2 - sentiment: positive - created_at: 2026-05-03 - updated_at: 2026-05-03 - playtime_hours: 33.1  cyberpunk more like cybergoth  ### Review 3 - senti
[4] source=hollow_knight.md | section=review | preview=this is the beast game for $15  ### Review 5 - sentiment: positive - created_at: 2026-05-03 - updated_at: 2026-05-03 - playtime_hours: 113.0  One of the best  ### Review 6 - sentiment: positive - created_at: 2026-05-03 - updated_at: 2026-05-03 - playtime_hours: 139.9  God tier indie game  ### Review

================================================================================
Intent: news
Query: No Man's Sky는 업데이트와 관련해서 어떤 내용이 있나요?
[1] source=no_mans_sky.md | section=news | preview=### News 4: No Man's Sky's latest update is a whole new Pokémon-style creature-collection and battle system that's 'an entire multiplayer game all of its own' - date: 2026-04-08  I'll just give it to you straight:  No Man's Sky  is Pokémon now. There's nothing you or I can do about it. Today's updat
[2] source=no_mans_sky.md | section=news | preview="Joke's on them," says No Man's Sky lead as rival survival game confirms it's replacing an eerily familiar cosmetic   New No Man's Sky update makes the most of its brilliant ship overhaul, giving you more reasons to explore the stars
[3] source=no_mans_sky.md | section=news | preview=### News 3: Introducing No Man's Sky Xeno Arena - date: 2026-04-08
[4] source=no_mans_sky.md | section=news | preview=## Steam News and Updates ### News 1: No Man's Sky channels a little Pokemon with the Xeno Arena update - date: 2026-04-14  No Man's Sky is steadily turning into the everything game isn't it? Hello Games have released another big upgrade for it recently adding creature battling. Read the full articl

In [19]:
from dotenv import load_dotenv
import os

load_dotenv(PROJECT_ROOT / ".env")

print("OPENAI_API_KEY exists:", bool(os.getenv("OPENAI_API_KEY")))

OPENAI_API_KEY exists: True

In [25]:
from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate

llm = ChatOpenAI(
    model="gpt-5-mini",
    temperature=0,
)

GAME_ALIASES = {
    "hollow_knight": [
        "hollow knight", "할로우 나이트", "할로우나이트"
    ],
    "monster_hunter_world": [
        "monster hunter: world", "monster hunter world",
        "몬스터 헌터 월드", "몬헌 월드", "몬헌월드"
    ],
    "baldurs_gate_3": [
        "baldur's gate 3", "baldurs gate 3",
        "발더스 게이트 3", "발더스3", "발더스 게이트"
    ],
    "no_mans_sky": [
        "no man's sky", "no mans sky",
        "노 맨즈 스카이", "노맨즈스카이"
    ],
    "cyberpunk_2077": [
        "cyberpunk 2077", "사이버펑크 2077",
        "사펑", "사이버펑크"
    ],
}


def detect_game_key(query: str):
    query_lower = query.lower()

    for game_key, aliases in GAME_ALIASES.items():
        for alias in aliases:
            if alias.lower() in query_lower:
                return game_key

    return None


def detect_intent(query: str):
    query_lower = query.lower()

    review_keywords = [
        "review", "reviews", "recent review", "steam review",
        "리뷰", "최근 리뷰", "평가", "반응", "유저 반응", "민심"
    ]

    news_keywords = [
        "update", "updates", "patch", "news", "recent update",
        "업데이트", "패치", "뉴스", "변경", "개선"
    ]

    if any(keyword in query_lower for keyword in review_keywords):
        return "review"

    if any(keyword in query_lower for keyword in news_keywords):
        return "news"

    return "general"


def build_filter(intent: str, game_key: str | None):
    """
    intent와 game_key를 바탕으로 Chroma metadata filter 생성.
    game_key가 있으면 반드시 해당 게임 문서 안에서만 검색한다.
    """
    conditions = []

    if intent == "review":
        conditions.append({"section": {"$eq": "review"}})
    elif intent == "news":
        conditions.append({"section": {"$eq": "news"}})

    if game_key is not None:
        conditions.append({"game_key": {"$eq": game_key}})

    if len(conditions) == 0:
        return None

    if len(conditions) == 1:
        return conditions[0]

    return {"$and": conditions}

In [26]:
rag_prompt = ChatPromptTemplate.from_messages(
    [
        (
            "system",
            """
You are a Steam game recommendation and analysis assistant.

Answer the user's question using only the provided context.
If the context is insufficient, say that the available document does not contain enough evidence.
Do not invent details that are not supported by the context.

Write the answer in Korean.
Keep the answer concise but grounded.
            """.strip(),
        ),
        (
            "human",
            """
[Question]
{question}

[Context]
{context}
            """.strip(),
        ),
    ]
)


def format_docs(docs):
    formatted = []

    for i, doc in enumerate(docs, start=1):
        source = Path(doc.metadata.get("source", "")).name
        section = doc.metadata.get("section", "unknown")
        game_key = doc.metadata.get("game_key", "unknown")
        content = doc.page_content

        formatted.append(
            f"[Context {i}]\n"
            f"source: {source}\n"
            f"game_key: {game_key}\n"
            f"section: {section}\n"
            f"{content}"
        )

    return "\n\n".join(formatted)


def retrieve_docs(query: str, k: int = 4):
    intent = detect_intent(query)
    game_key = detect_game_key(query)
    metadata_filter = build_filter(intent=intent, game_key=game_key)

    if metadata_filter is None:
        retrieved_docs = vectorstore.similarity_search(
            query=query,
            k=k,
        )
    else:
        retrieved_docs = vectorstore.similarity_search(
            query=query,
            k=k,
            filter=metadata_filter,
        )

    return intent, game_key, metadata_filter, retrieved_docs


def run_rag(query: str, k: int = 4):
    intent, game_key, metadata_filter, retrieved_docs = retrieve_docs(query, k=k)

    context = format_docs(retrieved_docs)

    messages = rag_prompt.format_messages(
        question=query,
        context=context,
    )

    response = llm.invoke(messages)

    return {
        "query": query,
        "intent": intent,
        "game_key": game_key,
        "metadata_filter": metadata_filter,
        "answer": response.content,
        "retrieved_docs": retrieved_docs,
        "context": context,
    }

In [27]:
result = run_rag("Cyberpunk 2077 최근 리뷰에서는 어떤 반응이 있나요?")

print("Intent:", result["intent"])
print("Game key:", result["game_key"])
print("Filter:", result["metadata_filter"])

print("\nAnswer:")
print(result["answer"])

print("\nRetrieved sources:")
for i, doc in enumerate(result["retrieved_docs"], start=1):
    print(
        i,
        Path(doc.metadata.get("source", "")).name,
        doc.metadata.get("game_key"),
        doc.metadata.get("section"),
    )

Intent: review
Game key: cyberpunk_2077
Filter: {'$and': [{'section': {'$eq': 'review'}}, {'game_key': {'$eq': 'cyberpunk_2077'}}]}

Answer:
최근 리뷰는 대체로 긍정적입니다.

주요 반응:
- 스토리·캐릭터·연출을 높이 평가 ("Such a beautiful and well-crafted story.", "Great story.")
- 몰입감·재미를 강조 ("Super fun and immersive game. Love getting lost in it.", "Its fun")
- 모딩 지원과 추가 실험을 추천하는 의견도 있음 ("Amazing modding support...")
- 플레이시간이 긴 리뷰들이 많아 높은 몰입/재방문도가 확인됨 (예: 197.4h, 302.4h, 702.6h 등)
- 간단한 찬사형 코멘트 다수 ("Great", "greatest game oat", "love this game")

전반적으로 최근 리뷰는 긍정적이고 만족도가 높은 편입니다.

Retrieved sources:
1 cyberpunk_2077.md cyberpunk_2077 review
2 cyberpunk_2077.md cyberpunk_2077 review
3 cyberpunk_2077.md cyberpunk_2077 review
4 cyberpunk_2077.md cyberpunk_2077 review

In [28]:
eval_questions = [
    "Hollow Knight는 어떤 플레이 스타일의 게임인가요?",
    "Hollow Knight의 분위기나 월드 구성은 어떤 특징이 있나요?",
    "Monster Hunter: World의 핵심 플레이 루프는 무엇인가요?",
    "Monster Hunter: World는 협동 플레이 측면에서 어떤 특징이 있나요?",
    "Baldur's Gate 3는 어떤 RPG인가요?",
    "Baldur's Gate 3에서 선택과 서사는 어떤 역할을 하나요?",
    "No Man's Sky는 업데이트와 관련해서 어떤 내용이 있나요?",
    "No Man's Sky의 최근 뉴스나 업데이트 방향은 무엇인가요?",
    "Cyberpunk 2077 최근 리뷰에서는 어떤 반응이 있나요?",
    "Cyberpunk 2077 문서에서 확인되는 주요 특징은 무엇인가요?",
]

len(eval_questions)

10

In [29]:
import pandas as pd

records = []

for q in eval_questions:
    print("=" * 80)
    print("Question:", q)

    result = run_rag(q)

    retrieved_info = []
    for doc in result["retrieved_docs"]:
        retrieved_info.append(
            {
                "source": Path(doc.metadata.get("source", "")).name,
                "section": doc.metadata.get("section", "unknown"),
                "preview": doc.page_content[:300].replace("\n", " "),
            }
        )

    records.append(
        {
            "question": q,
            "intent": result["intent"],
            "answer": result["answer"],
            "retrieved_sources": json.dumps(retrieved_info, ensure_ascii=False),
        }
    )

    print("Intent:", result["intent"])
    print("Answer:", result["answer"][:500])
    print()

eval_df = pd.DataFrame(records)
eval_df

================================================================================
Question: Hollow Knight는 어떤 플레이 스타일의 게임인가요?
Intent: general
Answer: Hollow Knight는 고전 스타일의 2D 횡스크롤 액션 어드벤처입니다. 타이트하게 튜닝된 조작으로 회피·대시·베기 중심의 전투를 즐기며, 넓고 상호 연결된 세계를 자유롭게 탐험하고 길을 개척해 나가는 플레이가 핵심입니다. 손으로 그린 고딕 풍의 세계와 기괴한 벌레들로 이루어진 지역들을 발견하고 NPC와 교류하거나 비밀을 풀어가는 요소도 있습니다. 싱글플레이 기반이며, 게임을 완료하면 더 높은 난이도의 Steel Soul Mode가 잠금 해제되는 등 도전 요소가 강한 편입니다.

================================================================================
Question: Hollow Knight의 분위기나 월드 구성은 어떤 특징이 있나요?
Intent: general
Answer: 짧게 요약하면 다음과 같습니다.

- 분위기: 음울하고 고딕한 정서가 강한 수공(手工)적 연출. 귀엽지만 오싹한 캐릭터들과 기괴하고 때로는 무서운 생물들이 등장하며, Christopher Larkin의 잔잔하면서도 애잔한 음악이 멸망한 문명의 장엄함과 슬픔을 강조합니다.
- 비주얼·연출: 전통 2D 손그림 애니메이션으로 세밀하게 표현된 지역들, 페인티드 풍경과 화려한 패럴랙스(입체감)가 옆보기 화면에 깊이감을 부여합니다.
- 월드 구성: 넓고 상호 연결된(Hub-like) 세계—뒤얽힌 동굴, 고대 도시, 버려진 고속로, 무성한 야생지, 폐허 등 다양한 구역이 연결되어 있고 각 구역이 독특하고 낯설게 설계되어 있습니다. 플레이어가 길을 선택해 스스로 길을 개척하는 탐험 중심 구조이며, 지도를 사고 업그레이드해 여정을 기록할 수 있는 풍부한 맵핑 시스템도 제공됩니다.
- 추가 요소: Dream Nail로 등장인물·적의 내면(다른 면모)을 파고들 수 있어 세계관의 미스터리를 더

================================================================================
Question: Monster Hunter: World의 핵심 플레이 루프는 무엇인가요?
Intent: general
Answer: 간단히 말하면 반복되는 핵심 루프는 다음과 같습니다.

1. 퀘스트를 받아 다양한 서식지로 출발한다.
2. 지형과 주변 생태계를 활용해 거대한 몬스터를 추적·교전한다.
3. 몬스터를 쓰러뜨리고 부위 파괴·채집으로 재료를 얻는다.
4. 수집한 재료로 무기·방어구 등 장비를 제작·강화해 더 강한 몬스터에 도전한다.

이 과정을 혼자 또는 최대 4인 협력으로 반복하며 점진적으로 난이도 높은 몬스터를 공략해 나가는 것이 핵심 플레이 루프입니다.

================================================================================
Question: Monster Hunter: World는 협동 플레이 측면에서 어떤 특징이 있나요?
Intent: general
Answer: Monster Hunter: World는 혼자 플레이할 수도 있고 최대 3명의 다른 플레이어와 함께(총 4인) 협동 사냥을 할 수 있습니다. 협동으로 퀘스트를 수행해 거대한 몬스터를 함께 쓰러뜨리고, 얻은 재료로 무기·방어구를 제작해 더 강한 몬스터에 도전할 수 있습니다.

================================================================================
Question: Baldur's Gate 3는 어떤 RPG인가요?
Intent: general
Answer: Baldur’s Gate 3는 던전 앤 드래곤즈 세계관을 바탕으로 한 스토리 중심의 파티 기반 RPG입니다. 플레이어의 선택이 동료 관계와 배신, 생존과 희생, 절대 권력의 유혹 등 이야기를 좌우하며, 높은 자유도로 탐험·실험·상호작용할 수 있는 개방적 시스템을 제공합니다. Divinity 4.0 엔진으로 제작된 영화적 내러티브와 그림자 저주 숲, 언더다크, 발더스 게이트 같은 다양한 지역을 무대로 하고 있으며, 싱글플레이는 물론 멀티·협동 플레이도 지원합니다.

================================================================================
Question: Baldur's Gate 3에서 선택과 서사는 어떤 역할을 하나요?
Intent: general
Answer: Baldur's Gate 3에서 선택은 서사의 핵심입니다. 플레이어의 행동과 선택이 모험의 전개와 최종적 유산을 결정하며(“your actions define the adventure, but your choices define your legacy”), 우정·배신·생존·희생·절대권력 같은 주제를 만들어냅니다. 엔진이 제공하는 높은 자유도로 탐험·실험·상호작용이 가능하고, 장대한 시네마틱 내러티브가 캐릭터들과의 유대감을 강화합니다. 동료들은 저마다의 도덕 기준으로 플레이어 선택에 반응하며, 캠프에서의 관계는 휴식이자 이후 결정들에 무게를 더합니다.

================================================================================
Question: No Man's Sky는 업데이트와 관련해서 어떤 내용이 있나요?
Intent: news
Answer: 간단히 요약하면 최근(2026년 4월) No Man's Sky 업데이트는 'Xeno Arena'로, 몬스터 수집·대전 요소를 본격적으로 추가했습니다.

주요 내용 (문서에 나온 것만)
- 업데이트 이름: Xeno Arena (발표·기사 날짜: 2026-04-08 ~ 04-14)
- 기존 게임에 포켓몬식의 생물 수집·배틀 시스템 추가
- 홀로아레나에서 외계 생물을 모아 서로 싸우게 할 수 있음(일부 기사에서는 이를 “완전한 멀티플레이어 게임” 수준이라고 표현)
- 전투 대상 생물 예시로 우주 소, 공룡, 기체형(가스 덩어리) 등 다양한 유형이 언급됨
- 업데이트가 기존의 훌륭한 함선(ship) 개편을 잘 활용해 탐사를 더 흥미롭게 만든다고 보도됨

제공된 문서 외의 자세한 변경점(밸런스, 수집 방식 등)은 해당 컨텍스트에 충분한 정보가 없습니다.

================================================================================
Question: No Man's Sky의 최근 뉴스나 업데이트 방향은 무엇인가요?
Intent: news
Answer: 최근 No Man's Sky 업데이트 방향은 'Xeno Arena'(2026년 4월 공개)를 중심으로 한 생물 수집·전투 시스템 도입입니다. 포켓몬 스타일로 외계 생물을 포획해 편대를 구성하고 홀로-아레나에서 서로 싸우게 하는 기능(멀티플레이어 성격을 띤 독립적인 콘텐츠)을 추가했으며, 우주선 대대적 개편과 연계해 탐험·전투 동기를 강화하는 방향을 취하고 있습니다. 기사들은 이를 “포켓몬식 전투”, “외계 동물들의 파이트클럽” 등으로 보도하고 있습니다.

================================================================================
Question: Cyberpunk 2077 최근 리뷰에서는 어떤 반응이 있나요?
Intent: review
Answer: 최근 스팀 리뷰는 대체로 긍정적입니다. 리뷰들에서 “재미있다/재밌음”, “몰입감 있다”, “멋진(잘 짜인) 스토리”, “좋은 캐릭터·모딩 지원” 등을 칭찬하는 의견이 많고(예: “Such a beautiful and well-crafted story”, “Super fun and immersive game”, “Great story”), 일부는 간단한 평(“its okay”)도 있지만 전체적으로 호평 위주입니다. 리뷰별 플레이 시간은 수시간부터 수백시간까지 다양합니다(예: 7.1h ~ 702.6h). 모든 최근 리뷰는 2026-05-03에 작성되어 있습니다.

================================================================================
Question: Cyberpunk 2077 문서에서 확인되는 주요 특징은 무엇인가요?
Intent: general
Answer: 문서에서 확인되는 주요 특징은 다음과 같습니다.

- 장르·무대: 오픈월드 액션 어드벤처 RPG로, 권력·화려함·신체 개조에 집착하는 미래 메갈로폴리스 "나이트 시티"를 배경으로 함.
- 버전·출시: Cyberpunk 2077: Ultimate Edition / 출시일 2020-12-09.
- 제작·배급: 개발·배급사 모두 CD PROJEKT RED.
- 스팀 메타정보: appid 1091500, 장르 RPG.
- 스팀 기능·접근성: 싱글플레이, 스팀 업적, 전체 컨트롤러 지원, 스팀 트레이딩 카드, 조절 가능한 글자 크기/볼륨/난이도, 카메라 편의·색상 대체, 타이밍 입력 불필요 모드, 언제든 저장, 자막, 스테레오·서라운드 사운드, HDR, Steam Cloud, 패밀리 공유 등.
- 최근 소식: Phantom Liberty DLC 관련 엔딩을 모드로 바꾼 사례(2026-04-29) 등 뉴스 기록이 있음.

,question,intent,answer,retrieved_sources
0,Hollow Knight는 어떤 플레이 스타일의 게임인가요?,general,Hollow Knight는 고전 스타일의 2D 횡스크롤 액션 어드벤처입니다. 타이트...,"[{""source"": ""hollow_knight.md"", ""section"": ""ab..."
1,Hollow Knight의 분위기나 월드 구성은 어떤 특징이 있나요?,general,짧게 요약하면 다음과 같습니다.\n\n- 분위기: 음울하고 고딕한 정서가 강한 수공...,"[{""source"": ""hollow_knight.md"", ""section"": ""ab..."
2,Monster Hunter: World의 핵심 플레이 루프는 무엇인가요?,general,간단히 말하면 반복되는 핵심 루프는 다음과 같습니다.\n\n1. 퀘스트를 받아 다양...,"[{""source"": ""monster_hunter_world.md"", ""sectio..."
3,Monster Hunter: World는 협동 플레이 측면에서 어떤 특징이 있나요?,general,Monster Hunter: World는 혼자 플레이할 수도 있고 최대 3명의 다른...,"[{""source"": ""monster_hunter_world.md"", ""sectio..."
4,Baldur's Gate 3는 어떤 RPG인가요?,general,Baldur’s Gate 3는 던전 앤 드래곤즈 세계관을 바탕으로 한 스토리 중심의...,"[{""source"": ""baldurs_gate_3.md"", ""section"": ""s..."
5,Baldur's Gate 3에서 선택과 서사는 어떤 역할을 하나요?,general,Baldur's Gate 3에서 선택은 서사의 핵심입니다. 플레이어의 행동과 선택이...,"[{""source"": ""baldurs_gate_3.md"", ""section"": ""s..."
6,No Man's Sky는 업데이트와 관련해서 어떤 내용이 있나요?,news,간단히 요약하면 최근(2026년 4월) No Man's Sky 업데이트는 'Xeno...,"[{""source"": ""no_mans_sky.md"", ""section"": ""news..."
7,No Man's Sky의 최근 뉴스나 업데이트 방향은 무엇인가요?,news,최근 No Man's Sky 업데이트 방향은 'Xeno Arena'(2026년 4월...,"[{""source"": ""no_mans_sky.md"", ""section"": ""news..."
8,Cyberpunk 2077 최근 리뷰에서는 어떤 반응이 있나요?,review,"최근 스팀 리뷰는 대체로 긍정적입니다. 리뷰들에서 “재미있다/재밌음”, “몰입감 있...","[{""source"": ""cyberpunk_2077.md"", ""section"": ""r..."
9,Cyberpunk 2077 문서에서 확인되는 주요 특징은 무엇인가요?,general,문서에서 확인되는 주요 특징은 다음과 같습니다.\n\n- 장르·무대: 오픈월드 액션...,"[{""source"": ""cyberpunk_2077.md"", ""section"": ""a..."

In [30]:
EVAL_DIR = PROJECT_ROOT / "data" / "eval"
EVAL_DIR.mkdir(parents=True, exist_ok=True)

output_csv = EVAL_DIR / "week3_baseline_results.csv"
eval_df.to_csv(output_csv, index=False, encoding="utf-8-sig")

print("saved:", output_csv)

saved: C:\Users\asguug\Documents\rag-agent\data\eval\week3_baseline_results.csv

In [31]:
ragas_questions = [
    "Hollow Knight는 어떤 플레이 스타일의 게임인가요?",
    "No Man's Sky는 업데이트와 관련해서 어떤 내용이 있나요?",
    "Cyberpunk 2077 최근 리뷰에서는 어떤 반응이 있나요?",
]

ragas_references = [
    "Hollow Knight는 2D 사이드스크롤 액션 어드벤처 게임으로, 거대한 연결형 세계를 탐험하고 적과 전투하며 고대 왕국의 비밀을 밝혀가는 플레이 스타일을 가진다.",
    "No Man's Sky는 지속적인 업데이트를 통해 새로운 콘텐츠와 시스템을 추가해 왔으며, 최근 뉴스에서는 새로운 업데이트와 게임 확장 방향이 언급된다.",
    "Cyberpunk 2077의 최근 Steam 리뷰는 대체로 긍정적인 반응이 많으며, 스토리, 캐릭터, 몰입감, 모딩 지원 등에 대한 호평이 확인된다.",
]

len(ragas_questions), len(ragas_references)

(3, 3)

In [32]:
ragas_records = []

for_q = list(zip(ragas_questions, ragas_references))

for question, reference in for_q:
    result = run_rag(question)

    contexts = [
        doc.page_content
        for doc in result["retrieved_docs"]
    ]

    ragas_records.append(
        {
            "question": question,
            "answer": result["answer"],
            "contexts": contexts,
            "ground_truth": reference,
            # 일부 RAGAS 버전 호환용 컬럼
            "user_input": question,
            "response": result["answer"],
            "retrieved_contexts": contexts,
            "reference": reference,
        }
    )

ragas_input_df = pd.DataFrame(ragas_records)

ragas_input_df[["question", "answer", "ground_truth"]]

,question,answer,ground_truth
0,Hollow Knight는 어떤 플레이 스타일의 게임인가요?,Hollow Knight는 클래식 스타일의 2D 사이드스크롤 액션 어드벤처입니다. ...,"Hollow Knight는 2D 사이드스크롤 액션 어드벤처 게임으로, 거대한 연결형..."
1,No Man's Sky는 업데이트와 관련해서 어떤 내용이 있나요?,"최근 No Man's Sky의 대규모 업데이트는 ""Xeno Arena""(2026년 ...",No Man's Sky는 지속적인 업데이트를 통해 새로운 콘텐츠와 시스템을 추가해 ...
2,Cyberpunk 2077 최근 리뷰에서는 어떤 반응이 있나요?,제공된 최근 스팀 리뷰들은 대체로 모두 긍정적입니다. 리뷰들에서 공통적으로 언급되는...,"Cyberpunk 2077의 최근 Steam 리뷰는 대체로 긍정적인 반응이 많으며,..."

In [33]:
from datasets import Dataset
from ragas import evaluate

from ragas.metrics import (
    faithfulness,
    answer_relevancy,
    context_precision,
    context_recall,
)

C:\Users\asguug\AppData\Local\Temp\ipykernel_30604\1486504553.py:4: DeprecationWarning: Importing faithfulness from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import faithfulness
  from ragas.metrics import (
C:\Users\asguug\AppData\Local\Temp\ipykernel_30604\1486504553.py:4: DeprecationWarning: Importing answer_relevancy from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import answer_relevancy
  from ragas.metrics import (
C:\Users\asguug\AppData\Local\Temp\ipykernel_30604\1486504553.py:4: DeprecationWarning: Importing context_precision from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import context_precision
  from ragas.metrics import (
C:\Users\asguug\AppData\Local\Temp\ipykernel_30604\1486504553.py:4: DeprecationWarning: Importing context_recall from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import context_recall
  from ragas.metrics import (

In [35]:
ragas_dataset = Dataset.from_dict(
    {
        "question": ragas_input_df["question"].tolist(),
        "answer": ragas_input_df["answer"].tolist(),
        "contexts": ragas_input_df["contexts"].tolist(),
        "ground_truth": ragas_input_df["ground_truth"].tolist(),
    }
)

ragas_dataset

Dataset({
    features: ['question', 'answer', 'contexts', 'ground_truth'],
    num_rows: 3
})

In [42]:
from ragas import evaluate
from ragas.llms import LangchainLLMWrapper
from ragas.embeddings import LangchainEmbeddingsWrapper

from langchain_openai import ChatOpenAI

from ragas.metrics import (
    faithfulness,
    answer_relevancy,
    context_precision,
    context_recall,
)

ragas_eval_llm = ChatOpenAI(
    model="gpt-4o-mini",
    temperature=0,
)

evaluator_llm = LangchainLLMWrapper(ragas_eval_llm)
evaluator_embeddings = LangchainEmbeddingsWrapper(embeddings)

metrics = [
    faithfulness,
    answer_relevancy,
    context_precision,
    context_recall,
]

# metric 객체에 평가용 LLM / embedding 명시 주입
for metric in metrics:
    if hasattr(metric, "llm"):
        metric.llm = evaluator_llm
    if hasattr(metric, "embeddings"):
        metric.embeddings = evaluator_embeddings

ragas_result = evaluate(
    ragas_dataset,
    metrics=metrics,
)

ragas_result

C:\Users\asguug\AppData\Local\Temp\ipykernel_30604\663037370.py:7: DeprecationWarning: Importing faithfulness from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import faithfulness
  from ragas.metrics import (
C:\Users\asguug\AppData\Local\Temp\ipykernel_30604\663037370.py:7: DeprecationWarning: Importing answer_relevancy from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import answer_relevancy
  from ragas.metrics import (
C:\Users\asguug\AppData\Local\Temp\ipykernel_30604\663037370.py:7: DeprecationWarning: Importing context_precision from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import context_precision
  from ragas.metrics import (
C:\Users\asguug\AppData\Local\Temp\ipykernel_30604\663037370.py:7: DeprecationWarning: Importing context_recall from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import context_recall
  from ragas.metrics import (
C:\Users\asguug\AppData\Local\Temp\ipykernel_30604\663037370.py:19: DeprecationWarning: LangchainLLMWrapper is deprecated and will be removed in a future version. Use llm_factory instead: from openai import OpenAI; from ragas.llms import llm_factory; llm = llm_factory('gpt-4o-mini', client=OpenAI(api_key='...'))
  evaluator_llm = LangchainLLMWrapper(ragas_eval_llm)
C:\Users\asguug\AppData\Local\Temp\ipykernel_30604\663037370.py:20: DeprecationWarning: LangchainEmbeddingsWrapper is deprecated and will be removed in a future version. Use the modern embedding providers instead: embedding_factory('openai', model='text-embedding-3-small', client=openai_client) or from ragas.embeddings import OpenAIEmbeddings, GoogleEmbeddings, HuggingFaceEmbeddings
  evaluator_embeddings = LangchainEmbeddingsWrapper(embeddings)

Evaluating:   0%|          | 0/12 [00:00<?, ?it/s]

LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.

{'faithfulness': 0.9259, 'answer_relevancy': 0.4284, 'context_precision': 1.0000, 'context_recall': 1.0000}